version: "3.9"

services:
  webserver:
    build:
      context: ./bin/${PHPVERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-${PHPVERSION}
    restart: "always"
    ports:
      - ${HOST_MACHINE_UNSECURE_HOST_PORT}:80
    links:
      - database
    env_file:
      - .env
    volumes:
      - ${PROJECT_ROOT-./../../../}:/var/www/html:rw
      - ${PROJECT_ROOT-./../../../}${DOCUMENT_ROOT-./public}:/var/www/html/public:rw
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      WEB_MASTER: ${WEB_MASTER}
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MYSQL_PORT}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  database:
    build:
      context: ./bin/${DATABASE}
    container_name: ${COMPOSE_PROJECT_NAME}-${DATABASE}
    restart: "always"
    ports:
      - 127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_INITDB_DIR-./config/initdb}:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - ${HOST_MACHINE_PMA_PORT}:80
    volumes:
      - /sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini